apiVersion: v1
kind: Service
metadata:
  name: platfomservice-srv
spec:
  type: NodePort
  selector:
    app: platfomservice
  ports:
    - name: platfomservice
      protocol: TCP
      port: 80
      targetPort: 80

